version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=super_password
      - POSTGRES_USER=programmer4876
      - POSTGRES_DB=chat
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - '54321:5432'
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./config/nginx
    ports:
      - '1000:1000'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    env_file:
      - .env
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      - postgres
    ports:
      - '5000:5000'
  socket:
    build:
      dockerfile: Dockerfile.dev
      context: ./socket
    env_file:
      - .env
    volumes:
      - /app/node_modules
      - ./socket:/app
    depends_on:
      - client
    ports:
      - '8900:8900'
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:3000'
